mutation createPasswordHistory($input: CreatePasswordHistoryInput!) {
  createPasswordHistory(input: $input) {
    ...PasswordHistoryDetails
  }
}

mutation deletePasswordHistory($passwordHistoryId: String!) {
  deletePasswordHistory(passwordHistoryId: $passwordHistoryId) {
    id
  }
}

mutation updatePasswordHistory($passwordHistoryId: String!, $input: UpdatePasswordHistoryInput!) {
  updatePasswordHistory(passwordHistoryId: $passwordHistoryId, input: $input) {
    ...PasswordHistoryDetails
  }
}
