query PasswordHistory($passwordHistoryId: String!) {
  passwordHistory(passwordHistoryId: $passwordHistoryId) {
    ...PasswordHistoryDetails
  }
}

query PasswordHistories($input: ListPasswordHistoryInput) {
  passwordHistories(input: $input) {
    ...PasswordHistoryList
  }
  counters: passwordHistoriesCount(input: $input) {
    ...CorePagingDetails
  }
}

query PasswordHistoryPagination($input: ListPasswordHistoryInput) {
  counters: passwordHistoriesCount(input: $input) {
    ...CorePagingDetails
  }
}
