mutation UserCreateUserPreference($input: SecureCreateUserPreferenceInput!) {
  userCreateUserPreference(input: $input) {
    ...UserPreferenceDetails
  }
}

mutation UserDeleteUserPreference($userPreferenceId: String!) {
  userDeleteUserPreference(userPreferenceId: $userPreferenceId) {
    id
  }
}

mutation UserUpdateUserPreference(
  $userPreferenceId: String!
  $input: SecureUpdateUserPreferenceInput!
) {
  userUpdateUserPreference(userPreferenceId: $userPreferenceId, input: $input) {
    ...UserPreferenceDetails
  }
}
