mutation __AdminCreatePasswordHistory($input: CreatePasswordHistoryInput!) {
  createPasswordHistory(input: $input) {
    ...__AdminPasswordHistoryDetails
  }
}

mutation __AdminDeletePasswordHistory($passwordHistoryId: String!) {
  deletePasswordHistory(passwordHistoryId: $passwordHistoryId) {
    id
  }
}

mutation __AdminUpdatePasswordHistory(
  $passwordHistoryId: String!
  $input: UpdatePasswordHistoryInput!
) {
  updatePasswordHistory(passwordHistoryId: $passwordHistoryId, input: $input) {
    ...__AdminPasswordHistoryDetails
  }
}
