mutation UploadUserAvatar($file: Upload!) {
  uploadUserAvatar(file: $file) {
    id
    url
    publicUrl
    filename
    originalName
    mimeType
    size
    width
    height
    provider
    folder
    metadata
    createdAt
  }
}

mutation UploadOrganizationLogo($file: Upload!) {
  uploadOrganizationLogo(file: $file) {
    id
    url
    publicUrl
    filename
    originalName
    mimeType
    size
    width
    height
    provider
    folder
    metadata
    createdAt
  }
}

mutation UploadFile($file: Upload!, $folder: String) {
  uploadFile(file: $file, folder: $folder) {
    id
    url
    publicUrl
    filename
    originalName
    mimeType
    size
    width
    height
    provider
    metadata
    createdAt
  }
}

mutation DeleteFile($uploadId: String!) {
  deleteFile(uploadId: $uploadId)
}

mutation RemoveOrganizationLogo {
  removeOrganizationLogo
}

mutation RemoveUserAvatar {
  removeUserAvatar
}
